### ISSUE TITLE
standing player model in addition to the boddy when a player dies

### ISSUE THREAD

**Issue by ValiusV** [Henit3/DramaMask#3] opened 2024-04-01 19:54 UTC
Clients seeing another player get killed by a monster or another player leave a standing player model in addition to the boddy. This bug does not occur for the host but is always present for the clients

**Comment by Henit3** [comment] 2024-04-01 23:07
Ah I ran into this before but couldn't replicate it so thought it was fixed by another change. Thanks for the steps to reproduce, will be fixed as part of the new update (paired along with some new features).

**Comment by Henit3** [comment] 2024-04-02 22:31
I've now patched this out, though since it is being included with the rest of the changes in the next update, it will take some time for it to be in the wild for you to test with. I'll mark it as complete for now, and can revert this status if you encounter it again after the update is out.

**Closed as completed by Henit3** 2024-04-02 22:31 UTC
Labels: bug

**Comment by ValiusV** [comment] 2024-04-03 09:05
Thank you for your work ! We will test the update and give you feedback to confirm the fix
