### ISSUE TITLE
Friends can't connect

### ISSUE THREAD

**Issue by LimerBoy** [Henit3/DramaMask#6] opened 2024-05-20 16:12 UTC
Friend cmd:
`
[Warning: Unity Log] [Netcode] NetworkObject (4) children not resolved to parents by the end of frame
[Info   : Unity Log] soumdmanager: True; False
`
My cmd:
`
[Info   : Unity Log] Connection approval callback! Game version of client request: 10000,76561198371569085
[Info   : Unity Log] Joining client id: 1; Local/host client id: 0
[Info   : Unity Log] Approved connection?: True. Connected players #: 1
[Info   : Unity Log] Disapproval reason:
[Warning: Unity Log] [Netcode] Deferred messages were received for a trigger of type OnSpawn with key 0, but that trigger was not received within within 1 second(s).
`

This happened after updating to: 2.0.9

**Comment by Henit3** [comment] 2024-05-20 17:14
Hey, could you reply with your profile code so I'm able to replicate and fix this?

The messages look unrelated to the changes, but I can take a look in case I did inadvertedly added this bug in.

**Comment by LimerBoy** [comment] 2024-05-20 17:51
seems not only yours mod makes this error. We disabled all then enabled one by one. 
018f9721-355b-3fa9-2868-f2b575accb70

**Comment by Henit3** [comment] 2024-05-20 21:23
I'm unable to replicate this on my end after using that profile code, adding in my mod + dependencies, and trying to host + join a lobby (no errors in console either).

I did notice dependencies were missing from some mods like no CSync and ToystoreInterior for Wesley's moons. Perhaps it's caused by this?

Unless it's narrowed down to this mod in particular, I'm closing this issue for now, since like I said, the logs you've shown don't seem to be related to the code affected by this mod anyway. Do let me know if this is shown to be worng ofc, with logs like you've done before, and I'll reopen if it looks like there is an issue after all.

**Closed as completed by Henit3** 2024-05-20 21:23 UTC
